// OutlookAddinProject.idl : IDL source for OutlookAddinProject
//

// This file will be processed by the MIDL tool to
// produce the type library (OutlookAddinProject.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(5933C7D6-C625-4B06-8009-A9147684CD22),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IConnect64 : IDispatch{
};
[
	uuid(F80C2F67-669B-40C9-9663-A109C20751E0),
	version(1.0),
]
library OutlookAddinLib64
{
	importlib("stdole2.tlb");
	[
		uuid(3C07CFA4-99FC-423B-8983-87AE8F40D3DF)		
	]
	coclass Connect64
	{
		[default] interface IConnect64;
	};
};

